server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: student_route1
          uri:  http://localhost:9080/
          predicates:
            - Path=/Hello/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9099/eureka